<a href="https://colab.research.google.com/github/rishikumar74/deeplearning/blob/main/Nlp_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.1)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.2)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 40.3 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0

In [2]:
from gensim.models import Word2Vec
sentences=[
    ["i","love","coding"],
    ["i","love","python"],
    ["python","is","powerful"]
]
#train CBOW model(sg=0)

cbow_model=Word2Vec(sentences,
                    min_count=1,
                    vector_size=5,#size of word vector
                    window=2,     #content window
                    sg=0)        #0-cbow
#get word vector
print("vector for coding")
print(cbow_model.wv["coding"])

#find similar words
print("similar to coding")
print(cbow_model.wv.most_similar("coding"))

vector for coding
[-0.06810732 -0.01892803  0.11537147 -0.15043275 -0.07872207]
similar to coding
[('love', 0.774187445640564), ('powerful', 0.766875147819519), ('python', -0.0006994431605562568), ('is', -0.15349125862121582), ('i', -0.6143277883529663)]

In [6]:
!pip install nltk
nltk.download('all')

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/abc.zip.
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/alpino.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_ru.zip.
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/averaged_perceptron_tagger_rus.zip.
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/basque_grammars.zip.
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/biocreative_ppi.zip.
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/bllip_wsj_no_aux.zip.
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/book_grammars.zip.
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown.zip.
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/brown_tei.zip.
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_cat.zip.
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cess_esp.zip.
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/chat80.zip.
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/city_database.zip.
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/cmudict.zip.
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/comparative_sentences.zip.
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2000.zip.
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/conll2002.zip.
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/crubadan.zip.
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dependency_treebank.zip.
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/dolch.zip.
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/english_wordnet.zip.
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/europarl_raw.zip.
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/floresta.zip.
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v15.zip.
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/framenet_v17.zip.
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gazetteers.zip.
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/genesis.zip.
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/gutenberg.zip.
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ieer.zip.
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/inaugural.zip.
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/indian.zip.
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/kimmo.zip.
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/large_grammars.zip.
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/lin_thesaurus.zip.
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mac_morpho.zip.
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker.zip.
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping chunkers/maxent_ne_chunker_tab.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/maxent_treebank_pos_tagger.zip.
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping
[nltk_data]    |       taggers/maxent_treebank_pos_tagger_tab.zip.
[nltk_data]    | Downloading package mock_corpus to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mock_corpus.zip.
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/moses_sample.zip.
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/movie_reviews.zip.
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/mte_teip5.zip.
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Unzipping misc/mwa_ppdb.zip.
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/names.zip.
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nonbreaking_prefixes.zip.
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/nps_chat.zip.
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/opinion_lexicon.zip.
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/paradigms.zip.
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pe08.zip.
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping misc/perluniprops.zip.
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pil.zip.
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pl196x.zip.
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/porter_test.zip.
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ppattach.zip.
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/problem_reports.zip.
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_1.zip.
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/product_reviews_2.zip.
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/pros_cons.zip.
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ptb.zip.
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt.zip.
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Unzipping tokenizers/punkt_tab.zip.
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/qc.zip.
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Unzipping stemmers/rslp.zip.
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/rte.zip.
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/sample_grammars.zip.
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/senseval.zip.
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentence_polarity.zip.
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sentiwordnet.zip.
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/shakespeare.zip.
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/sinica_treebank.zip.
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/smultron.zip.
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping grammars/spanish_grammars.zip.
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/state_union.zip.
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/stopwords.zip.
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/subjectivity.zip.
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/swadesh.zip.
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/switchboard.zip.
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets.zip.
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping help/tagsets_json.zip.
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/timit.zip.
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/toolbox.zip.
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/treebank.zip.
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/twitter_samples.zip.
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr.zip.
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/udhr2.zip.
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping corpora/unicode_samples.zip.
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping taggers/universal_tagset.zip.
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet.zip.
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/verbnet3.zip.
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/webtext.zip.
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Unzipping models/wmt15_eval.zip.
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Unzipping models/word2vec_sample.zip.
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet2022.zip.
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/wordnet_ic.zip.
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/words.zip.
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Unzipping corpora/ycoe.zip.
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [9]:
import nltk
sentence="Elonmusk visited India"

words=nltk.word_tokenize(sentence)
pos_tag=nltk.pos_tag(words)

ner_tree=nltk.ne_chunk(pos_tag)
print(ner_tree)

(S (PERSON Elonmusk/NNP) visited/VBD (GPE India/NNP))

In [10]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 70.8 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [14]:
import spacy
nlp=spacy.load("en_core_web_sm")
doc=nlp("Elon musk founded tesla in california")
for ent in doc.ents:
  print(ent.text,"->",ent.label_)

california -> GPE

In [19]:
!python -m spacy download en_core_web_md

Collecting en-core-web-md==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl (33.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 33.5/33.5 MB 56.4 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_md')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [20]:
import spacy
nlp=spacy.load("en_core_web_md")
doc=nlp("Elon musk founded tesla in california")
for ent in doc.ents:
  print(ent.text,"->",ent.label_)

Elon -> PRODUCT
california -> GPE

In [21]:
from google.colab import drive
import pandas as pd

drive.mount('/content/drive')

df = pd.read_csv('/content/spam (1).csv', encoding='latin1')
df.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,v1,v2,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,ham,"Go until jurong point, crazy.. Available only ...",NaN,NaN,NaN
1,ham,Ok lar... Joking wif u oni...,NaN,NaN,NaN
2,spam,Free entry in 2 a wkly comp to win FA Cup fina...,NaN,NaN,NaN
3,ham,U dun say so early hor... U c already then say...,NaN,NaN,NaN
4,ham,"Nah I don't think he goes to usf, he lives aro...",NaN,NaN,NaN

In [22]:
df.shape

(5572, 5)

In [23]:
df.count()

v1            5572
v2            5572
Unnamed: 2      50
Unnamed: 3      12
Unnamed: 4       6
dtype: int64

In [24]:
df['v1'].count()

np.int64(5572)

In [25]:
df=df[['v1','v2']]
df.columns=['labels','cols']

In [26]:
df.head()

  labels                                               cols
0    ham  Go until jurong point, crazy.. Available only ...
1    ham                      Ok lar... Joking wif u oni...
2   spam  Free entry in 2 a wkly comp to win FA Cup fina...
3    ham  U dun say so early hor... U c already then say...
4    ham  Nah I don't think he goes to usf, he lives aro...

In [28]:
df['labels'].value_counts()

labels
ham     4825
spam     747
Name: count, dtype: int64

In [29]:
df['len']=df['cols'].apply(len)
print(df['len'].mean())

80.11880832735105

/tmp/ipykernel_580/2547155821.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['len']=df['cols'].apply(len)

Lowercasing
Tokenization
Stopword removal
Punctuation removal
Lemmatization

In [30]:
import nltk
nltk.download('all')
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
import string
stop_words = set(stopwords.words('english'))
le=WordNetLemmatizer()

def Lowercasing(word) :
  word=word.lower()
  return word

def Tokenization(word) :
  return word_tokenize(word)

def StopwordRem(toks):
  return [tok for tok in toks if tok not in stop_words]

def RemPuncuations(words) :
  return [word for word in words if word not in string.punctuation]

def Lemmatization(words) :
  return [le.lemmatize(word) for word in words]


for words in df['cols']:
  word=Lowercasing(words)
  tok=Tokenization(word)
  v2=StopwordRem(tok)
  v3=RemPuncuations(v2)
  v4=Lemmatization(v3)
  print(v4)

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package mock_corpus to /root/nltk_data...
[nltk_data]    |   Package mock_corpus is already up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Package wordnet2022 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection all

Streaming output truncated to the last 5000 lines.
['open', 'door']
['waiting', 'call']
['nope', 'waiting', 'sch', '4', 'daddy', '...']
['1,000', 'cash', '2,000', 'prize', 'claim', 'call09050000327']
["'m", 'tired', 'arguing', 'week', 'week', 'want', "'ll"]
['ìï', 'wait', '4', 'sch', 'finish', 'ard', '5', '..']
['mobile', 'number', 'å£5000', 'claim', 'call', 'u', 'back', 'ring', 'claim', 'hot', 'line', '09050005321']
['arngd', 'marriage', 'u', 'r', 'walkin', 'unfortuntly', 'snake', 'bite', 'u.', 'bt', 'love', 'marriage', 'dancing', 'frnt', 'snake', 'amp', 'sayin', 'bite', 'bite']
['huh', 'early', '..', 'ì_', 'dinner', 'outside', 'izzit']
['ok', 'anyway', 'need', 'change', 'said']
['tried', 'contact', 'reply', 'offer', '750', 'min', '150', 'textand', 'new', 'video', 'phone', 'call', '08002988890', 'reply', 'free', 'delivery', 'tomorrow']
['ex-wife', 'able', 'kid', 'want', 'kid', 'one', 'day']
["'s", 'scotland', 'hope', 'showing', 'jjc', 'tendency', 'take', 'care', 'live', 'dream']
['tell', 'u', 'headache', 'want', 'use', '1', 'hour', 'sick', 'time']
['dun', 'thk', "'ll", 'quit', 'yet', '...', 'hmmm', 'go', 'jazz', 'yogasana', 'oso', '...', 'go', 'meet', 'em', 'lesson', 'den', '...']
['\\pete', 'please', 'ring', 'meive', 'hardly', 'gotany', 'credit\\', "''", "''"]
['ya', 'srsly', 'better', 'yi', 'tho']
["'m", 'meeting', 'call', 'later']
['ur', 'chance', 'win', 'å£250', 'wkly', 'shopping', 'spree', 'txt', 'shop', '80878.', "'s", 'c', "'s", 'www.txt-2-shop.com', 'custcare', '08715705022', '1x150p/wk']
['specially', 'selected', 'receive', '2000', 'pound', 'award', 'call', '08712402050', 'line', 'close', 'cost', '10ppm', '16+', 'c', 'apply', 'ag', 'promo']
['private', '2003', 'account', 'statement', '07753741225', 'show', '800', 'un-redeemed', 's.', 'i.', 'm.', 'point', 'call', '08715203677', 'identifier', 'code', '42478', 'expires', '24/10/04']
['still', 'grand', 'prix']
['met', 'stranger', 'choose', 'friend', 'long', 'world', 'stand', 'friendship', 'never', 'end', 'let', 'friend', 'forever', 'gud', 'nitz', '...']
['great']
['gud', 'mrng', 'dear', 'nice', 'day']
['important', 'customer', 'service', 'announcement', 'call', 'freephone', '0800', '542', '0825']
['exhausted', 'train', 'morning', 'much', 'wine', 'pie', 'sleep', 'well']
["'m", 'going', 'buy', 'mum', "'s", 'present', 'ar']
['mind', 'blastin', '..', 'tsunami', 'occur', '..', 'rajnikant', 'stopped', 'swimming', 'indian', 'ocean', '..', '-d']
['u', 'sending', 'home', 'first', "'s", 'ok', 'lor', "'m", 'ready', 'yet']
['speaking', 'cash', 'yet']
['happy', 'come', 'noon']
['meet', 'lunch', 'la', '...']
['take', 'care', 'n', 'get', 'well', 'soon']
['xclusive', 'clubsaisai', '2morow', '28/5', 'soiree', 'speciale', 'zouk', 'nichols', 'paris.free', 'rose', '2', 'lady', 'info', '07946746291/07880867867']
['meant', 'say', 'cant', 'wait', 'see', 'u', 'getting', 'bored', 'bridgwater', 'banter']
['neva', 'mind', "'s", 'ok', '..']
["'s", 'fine', 'imma', 'get', 'drink', 'somethin', 'want', 'come', 'find']
['22', 'day', 'kick', 'euro2004', 'u', 'kept', 'date', 'latest', 'news', 'result', 'daily', 'removed', 'send', 'get', 'txt', 'stop', '83222']
['valentine', 'game', 'send', 'dis', 'msg', 'ur', 'friend', '..', '5', 'answer', 'r', 'someone', 'really', 'love', 'u.', 'ques-', 'colour', 'suit', 'best', 'rply']
['many', 'dependent']
['thanx4', 'today', 'cer', 'nice', '2', 'catch', 'ave', '2', 'find', 'time', 'often', 'oh', 'well', 'take', 'care', 'c', 'u', 'soon.c']
['called', 'said', 'choose', 'future']
['\\happy', 'valentine', 'day\\', "''", 'know', 'early', 'hundred', 'handsomes', 'beauty', 'wish', 'thought', 'finish', 'aunty', 'uncle', '1st', '...', "''"]
['like', 'v', 'shock', 'leh', 'co', 'telling', 'shuhui', 'like', 'telling', 'leona', 'also', 'like', 'dat', 'almost', 'know', 'liao', 'got', 'ask', 'abt', 'ur', 'reaction', 'lor']
['family', 'happiness', '..']
['come', 'n', 'pick', 'ì_', '...', 'come', 'immediately', 'aft', 'ur', 'lesson', '...']
['let', 'snow', 'let', 'snow', 'kind', 'weather', 'brings', 'ppl', 'together', 'friendship', 'grow']
['dear', 'got', 'lt', 'gt', 'dollar', 'hi', 'hi']
['good', 'word', '....', 'word', 'may', 'leave', 'u', 'dismay', 'many', 'time']
['make', 'sure', 'alex', 'know', 'birthday', 'fifteen', 'minute', 'far', "'re", 'concerned']
['sorry', 'got', 'thing', 'may', 'pub', 'later']
['nah', "'s", 'straight', 'bring', 'bud', 'drink', 'something', "'s", 'actually', 'little', 'useful', 'straight', 'cash']
['haha', 'good', 'hear', "'m", 'officially', 'paid', 'market', '8th']
['many', 'lick', 'take', 'get', 'center', 'tootsie', 'pop']
['yup', 'thk', 'r', 'e', 'teacher', 'said', 'make', 'face', 'look', 'longer', 'darren', 'ask', '2', 'cut', 'short']
['new', 'textbuddy', 'chat', '2', 'horny', 'guy', 'ur', 'area', '4', '25p', 'free', '2', 'receive', 'search', 'postcode', 'gaytextbuddy.com', 'txt', 'one', 'name', '89693']
['today', 'vodafone', 'number', 'ending', '4882', 'selected', 'receive', 'å£350', 'award', 'number', 'match', 'call', '09064019014', 'receive', 'å£350', 'award']
['please', 'dont', 'say', 'like', 'hi', 'hi', 'hi']
['thank', 'u']
['oh', 'forwarded', 'message', 'thought', 'send']
['got', 'seventeen', 'pound', 'seven', 'hundred', 'ml', '\x89ûò', 'hope', 'ok']
['dear', 'voucher', 'holder', '2', 'claim', 'week', 'offer', 'pc', 'go', 'http', '//www.e-tlp.co.uk/expressoffer', 't', 'c', 'apply.2', 'stop', 'text', 'txt', 'stop', '80062']
['n', 'funny', '...']
['sweetheart', 'hope', 'kind', 'day', 'one', 'load', 'reason', 'smile', 'biola']
['ì_', 'login', 'dat', 'time', '...', 'dad', 'fetching', 'ì_', 'home']
['shower', 'baby']
['askd', 'u', 'question', 'hour', 'answer']
['well', 'imma', 'definitely', 'need', 'restock', 'thanksgiving', "'ll", 'let', 'know', "'m"]
['said', 'kiss', 'kiss', 'ca', "n't", 'sound', 'effect', 'gorgeous', 'man', "n't", 'kind', 'person', 'need', 'smile', 'brighten', 'day']
['probably', 'gon', 'na', 'swing', 'wee', 'bit']
['ya', 'nice', '.be', 'ready', 'thursday']
['allo', 'braved', 'bus', 'taken', 'train', 'triumphed', 'mean', 'we\x89û÷re', 'b\x89û÷ham', 'jolly', 'good', 'rest', 'week']
['watching', 'cartoon', 'listening', 'music', 'amp', 'eve', 'go', 'temple', 'amp', 'church', '..', 'u']
['mind', 'ask', 'happened', 'dont', 'say', 'uncomfortable']
['private', '2003', 'account', 'statement', 'show', '800', 'un-redeemed', 's.', 'i.', 'm.', 'point', 'call', '08715203694', 'identifier', 'code', '40533', 'expires', '31/10/04']
['prob', 'send', 'email']
['1,000', 'cash', '2,000', 'prize', 'claim', 'call09050000327', 'c', 'rstm', 'sw7', '3ss', '150ppm']
['thats', 'cool', 'sometimes', 'slow', 'gentle', 'sonetimes', 'rough', 'hard']
["'m", 'gon', 'na', 'say', 'sorry', 'would', 'normal', 'starting', 'panic', 'time', 'sorry', 'seeing', 'tuesday']
['wait', 'know', 'wesley', 'town', 'bet', 'hella', 'drug']
['fine', 'miss', 'much']
['u', 'got', 'person', 'story']
['tell', 'drug', 'dealer', "'s", 'getting', 'impatient']
['sun', 'cant', 'come', 'earth', 'send', 'luv', 'ray', 'cloud', 'cant', 'come', 'river', 'send', 'luv', 'rain', 'cant', 'come', 'meet', 'u', 'send', 'care', 'msg', 'u.', 'gud', 'evng']
['place', 'man']
['doesnt', 'make', 'sense', 'take', 'unless', 'free', 'need', 'know', 'wikipedia.com']
['88800', '89034', 'premium', 'phone', 'service', 'call', '08718711108']
['sea', 'lay', 'rock', 'rock', 'envelope', 'envelope', 'paper', 'paper', '3', 'word', '...']
['mum', "'s", 'repent']
['sorry', 'going', 'home', 'first', '...', 'daddy', 'come', 'fetch', 'ì_', 'later', '...']
['leave', 'de', 'start', 'prepare', 'next', '..']
['yes', 'baby', 'study', 'position', 'kama', 'sutra']
['en', 'chikku', 'nange', 'bakra', 'msg', 'kalstiya', '..', 'tea/coffee']
['carlos', "'ll", 'minute', 'still', 'need', 'buy']
['pay', 'lt', 'decimal', 'gt', 'lakh']
['good', 'evening', 'ttyl']
['u', 'receive', 'msg']
['ho', 'ho', 'big', 'belly', 'laugh', 'see', 'ya', 'tomo']
['sm', 'ac', 'sun0819', 'post', 'hello', '\\you', 'seem', 'cool']
['get', 'ur', '1st', 'ringtone', 'free', 'reply', 'msg', 'tone', 'gr8', 'top', '20', 'tone', 'phone', 'every', 'week', 'å£1.50', 'per', 'wk', '2', 'opt', 'send', 'stop', '08452810071', '16']
['ditto', 'wo', "n't", 'worry', 'saying', 'anything', 'anymore', 'like', 'said', 'last', 'night', 'whatever', 'want', "'ll", 'peace']
["'ve", 'got', 'lt', 'gt', 'way', 'could', 'pick']
['dont', 'knw', 'pa', 'drink', 'milk', '..']
['maybe', 'say', 'hi', 'find', 'got', 'card', 'great', 'escape', 'wetherspoons']
['piggy', 'r', 'u', 'awake', 'bet', 'u', "'re", 'still', 'sleeping', "'m", 'going', '4', 'lunch', '...']
['cause', "'m", 'freaky', 'lol']
['missed', 'call', 'cause', 'yelling', 'scrappy', 'miss', 'u.', 'ca', "n't", 'wait', 'u', 'come', 'home', "'m", 'lonely', 'today']
["'hex", 'place', 'talk', 'explain']
['ìï', 'log', '4', 'wat', "'s", 'sdryb8i']
['xy', 'going', '4', 'e', 'lunch']
['hi', "'m", 'sue', '20', 'year', 'old', 'work', 'lapdancer', 'love', 'sex', 'text', 'live', "'m", 'bedroom', 'text', 'sue', '89555.', 'textoperator', 'g2', '1da', '150ppmsg', '18+']
['wanted', 'ask', 'ì_', 'wait', '4', 'finish', 'lect', 'co', 'lect', 'finish', 'hour', 'anyway']
['finished', 'work', 'yet']
['every', 'king', 'cry', 'baby', 'every', 'great', 'building', 'map', '..', 'imprtant', 'u', 'r', 'today', 'u', 'wil', 'reach', 'tomorw', 'gud', 'ni8']
['dear', 'cherthala.in', 'case', 'u', 'r', 'coming', 'cochin', 'pls', 'call', 'bfore', 'u', 'start.i', 'shall', 'also', 'reach', 'accordingly.or', 'tell', 'day', 'u', 'r', 'coming.tmorow', 'engaged', 'an', 'holiday']
['thanks', 'love', 'torch', 'bold']
['forwarded', '448712404000', 'please', 'call', '08712404000', 'immediately', 'urgent', 'message', 'waiting']
['farm', 'open']
['sorry', 'trouble', 'u', 'buy', '4d', 'dad', '1405', '1680', '1843.', '2', 'big', '1', 'small', 'sat', 'n', 'sun', 'thanx']
['sister', 'law', 'hope', 'great', 'month', 'saying', 'hey', 'abiola']
['purchase', 'stuff', 'today', 'mail', 'po', 'box', 'number']
['ah', 'poop', 'look', 'like', 'ill', 'prob', 'send', 'laptop', 'get', 'fixed', 'cuz', 'gpu', 'problem']
['good', 'good', 'job', 'like', 'entrepreneur']
['aight', 'close', 'still', 'around', 'alex', "'s", 'place']
['meet', 'corporation', 'st', 'outside', 'gap', '\x89û_', 'see', 'mind', 'working']
['mum', 'ask', 'ì_', 'buy', 'food', 'home', '...']
['k', '..', 'u', 'also', 'dont', 'msg', 'reply', 'msg', '..']
['much', 'r', 'ì_', 'willing', 'pay']
['sorry', "'ll", 'call', 'later']
['important', 'prevent', 'dehydration', 'giving', 'enough', 'fluid']
['thats', 'bit', 'weird', 'even', 'supposed', 'happening', 'good', 'idea', 'sure', 'pub']
['true', 'dear', '..', 'sat', 'pray', 'evening', 'felt', 'so.so', 'sm', "'d", 'time', '...']
["n't", 'think', 'get', 'away', 'trek', 'long', 'family', 'town', 'sorry']
['wan', 'na', 'gym', 'harri']
['quite', 'late', 'lar', '...', 'ard', '12', 'anyway', 'wun', 'b', 'drivin', '...']
['review', 'keep', 'fantastic', 'nokia', 'n-gage', 'game', 'deck', 'club', 'nokia', 'go', '2', 'www.cnupdates.com/newsletter', 'unsubscribe', 'alert', 'reply', 'word']
['4mths', 'half', 'price', 'orange', 'line', 'rental', 'latest', 'camera', 'phone', '4', 'free', 'phone', '11mths+', 'call', 'mobilesdirect', 'free', '08000938767', 'update', 'or2stoptxt', 'c']
['height', 'confidence', 'aeronautics', 'professor', 'wer', 'calld', 'amp', 'wer', 'askd', '2', 'sit', 'aeroplane', 'aftr', 'sat', 'wer', 'told', 'dat', 'plane', 'w', 'made', 'student', 'dey', 'hurried', 'plane', '..', 'bt', '1', 'didnt', 'move', '...', 'said', '\\if', 'made', 'student']
['seems', 'like', 'weird', 'timing', 'night', 'g', 'want', 'come', 'smoke', 'day', 'shitstorm', 'attributed', 'always', 'coming', 'making', 'everyone', 'smoke']
['08714712388', '10am-7pm', 'cost', '10p']
['save', 'stress', 'person', 'dorm', 'account', 'send', 'account', 'detail', 'money', 'sent']
['also', 'know', 'lunch', 'menu', 'da', 'know']
['stuff', 'sell', 'i.ll', 'tell']
['+449071512431', 'urgent', '2nd', 'attempt', 'contact', 'u', 'u', 'å£1250', 'call', '09071512433', 'b4', '050703', 'csbcm4235wc1n3xx', 'callcost', '150ppm', 'mobilesvary', 'maxå£7', '50']
['book', 'lesson', 'msg', '...', 'call', 'work', 'sth', '...', "'m", 'going', 'get', 'spec', 'membership', 'px3748']
['guaranteed', 'å£1000', 'cash', 'å£2000', 'prize', 'claim', 'yr', 'prize', 'call', 'customer', 'service', 'representative', '08714712394', '10am-7pm']
['macha', 'dont', 'feel', 'upset.i', 'assume', 'mindset.believe', 'one', 'evening', 'wonderful', 'plan', 'us.let', 'life', 'begin', 'again.call', 'anytime']
['oh', 'send', 'address']
["s'fine", 'anytime', 'best']
['wondar', 'full', 'flim']
['ya', 'even', 'cooky', 'jelly']
['world', 'running', 'still.maybe', 'feeling', 'it.or', 'admit', 'mad.then', 'correction', 'let', 'call', 'life.and', 'keep', 'running', 'world', 'may', 'u', 'r', 'also', 'running.lets', 'run']
['got', 'look', 'scrumptious', '...', 'daddy', 'want', 'eat', 'night', 'long']
['co', 'lar', "'m", 'ba', 'dao', 'ok', '...', '1', 'pm', 'lor', '...', 'u', 'never', 'ask', 'go', 'ah', '...', 'said', 'u', 'would', 'ask', 'fri', 'said', 'u', 'ask', 'today', '...']
['alright', 'omw', 'got', 'ta', 'change', 'order', 'half8th']
['exactly', 'anyways', 'far', 'jide', 'study', 'visiting']
['dunno', 'u', 'ask']
['email', 'alertfrom', 'jeri', 'stewartsize', '2kbsubject', 'low-cost', 'prescripiton', 'drvgsto', 'listen', 'email', 'call', '123']
["n't", 'spring', 'coming', 'early', 'yay']
['lol', 'wo', "n't", 'feel', 'bad', 'use', 'money', 'take', 'steak', 'dinner', '=d']
['even', 'u', 'dont', 'get', 'trouble', 'convincing', '..', 'tel', 'twice', 'tel', 'neglect', 'msg', 'dont', 'c', 'read', '..', 'dont', 'reply']
['leaving', 'qatar', 'tonite', 'search', 'opportunity.all', 'went', 'fast.pls', 'add', 'ur', 'prayer', 'dear.rakhesh']
['one', 'talking']
['thanks', 'looking', 'really', 'appreciate']
['hi', 'customer', 'loyalty', 'offer', 'new', 'nokia6650', 'mobile', 'å£10', 'txtauction', 'txt', 'word', 'start', '81151', 'get', '4t', 'ctxt', 'tc', '150p/mtmsg']
['wish']
['haha', 'mayb', 'u', "'re", 'rite', '...', 'u', 'know', 'well', 'da', 'feeling', 'liked', 'someone', 'gd', 'lor', 'u', 'faster', 'go', 'find', 'one', 'gal', 'group', 'attached', 'liao']
['yes', 'glad', 'made']
['well', 'little', 'time', 'thing', 'good', 'time', 'ahead']
['got', 'room', 'soon', '\x89û_', "n't", 'put', 'clock', 'back', 'til', '8', 'shouted', 'everyone', 'get', 'realised', '7.', 'wahay', 'another', 'hour', 'bed']
['ok.', 'may', 'free', 'gym']
['men', 'like', 'shorter', 'lady', 'gaze', 'eye']
['dunno', 'jus', 'say', 'go', 'lido', 'time', '930']
['promise', 'take', 'good', 'care', 'princess', 'run', 'please', 'send', 'pic', 'get', 'chance', 'ttyl']
['u', 'subscribed', 'best', 'mobile', 'content', 'service', 'uk', 'å£3', 'per', '10', 'day', 'send', 'stop', '82324.', 'helpline', '08706091795']
['reason', "'ve", 'spoken', 'year', 'anyways', 'great', 'week', 'best', 'exam']
['monday', 'next', 'week', 'give', 'full', 'gist']
['realize', '40', 'year', "'ll", 'thousand', 'old', 'lady', 'running', 'around', 'tattoo']
['important', 'customer', 'service', 'announcement', 'premier']
['dont', 'gim', 'lip', 'caveboy']
['get', 'library']
['realy', 'sorry-i', "n't", 'recognise', 'number', 'confused', 'r', 'u', 'please']
['didnt', 'holla']
['cant', 'think', 'anyone', 'spare', 'room', 'top', 'head']
['faith', 'make', 'thing', 'possible', 'hope', 'make', 'thing', 'work', 'love', 'make', 'thing', 'beautiful', 'may', 'three', 'christmas', 'merry', 'christmas']
['u', 'made', 'appointment']
['call', 'you/carlos', 'is/are', 'phone', "'s", 'vibrate', 'acting', 'might', 'hear', 'text']
['romantic', 'paris', '2', 'night', '2', 'flight', 'å£79', 'book', '4', 'next', 'year', 'call', '08704439680ts', 'c', 'apply']
['grandma', 'oh', 'dear', 'u', 'still', 'ill', 'felt', 'shit', 'morning', 'think', 'hungover', 'another', 'night', 'leave', 'sat']
['urgent', 'ur', 'å£500', 'guaranteed', 'award', 'still', 'unclaimed', 'call', '09066368327', 'closingdate04/09/02', 'claimcode', 'm39m51', 'å£1.50pmmorefrommobile2bremoved-mobypobox734ls27yf']
['nothing', 'jus', 'tot', 'u', 'would', 'ask', 'co', 'u', 'ba', 'gua', '...', 'went', 'mt', 'faber', 'yest', '...', 'yest', 'jus', 'went', 'already', 'mah', 'today', 'going', '...', 'jus', 'call', 'lor', '...']
['wishing', 'family', 'merry', '\\x\\', "''", 'ma', 'happy', 'new', 'year', 'advance', '..', "''"]
['ur', 'awarded', 'city', 'break', 'could', 'win', 'å£200', 'summer', 'shopping', 'spree', 'every', 'wk', 'txt', 'store', '88039', 'skilgme', 'tscs087147403231winawk', 'age16', 'å£1.50perwksub']
["'m", 'nt', 'goin', 'got', 'somethin', 'unless', 'meetin', '4', 'dinner', 'lor', '...', 'haha', 'wonder', 'go', 'ti', 'time', '...']
['sorry', "'ll", 'call', 'later']
['cant', 'pick', 'phone', 'right', 'pls', 'send', 'message']
['lol', 'know', "'re", 'dramatic', 'school', 'already', 'closed', 'tomorrow', 'apparently', 'ca', "n't", 'drive', 'inch', 'snow', 'supposed', 'get']
['getting', 'anywhere', 'damn', 'job', 'hunting']
['lol', 'u', 'drunkard', 'hair', 'moment', 'yeah', 'still', '4', 'tonight', 'wats', 'plan']
['idc', 'get', 'weaseling', 'way', 'shit', 'twice', 'row']
['wil', 'lt', 'gt', 'minute', 'got', 'space']
['sleeping', '..', 'surfing']
['thanks', 'picking', 'trash']
["n't", 'go', 'tell', 'friend', "'re", 'sure', 'want', 'live', 'smoke', 'much', 'spend', 'hour', 'begging', 'come', 'smoke']
['\\hi', 'kate', 'lovely', 'see', 'tonight', 'ill', 'phone', 'tomorrow', 'got', 'sing', 'guy', 'gave', 'card', 'xxx\\', "''", "''"]
['happy', 'new', 'year', 'dear', 'brother', 'really', 'miss', 'got', 'number', 'decided', 'send', 'text', 'wishing', 'happiness', 'abiola']
['mean', 'get', 'door']
['opinion', '1.', '2.', 'jada', '3.', 'kusruthi', '4.', 'lovable', '5.', 'silent', '6.', 'spl', 'character', '7.', 'matured', '8.', 'stylish', '9.', 'simple', 'pls', 'reply', '..']
['hmmm', '...', 'thought', 'said', '2', 'hour', 'slave', '3', '...', 'late', '...', 'punish']
['beerage']
['important', 'customer', 'service', 'announcement', 'premier', 'call', 'freephone', '0800', '542', '0578']
['dont', 'think', 'turn', 'like', 'randomlly', 'within', '5min', 'opening']
['supposed', 'could', "n't", 'make', "'s", 'still', 'town', 'though']
['time', 'fix', 'spelling', 'sometimes', 'get', 'completely', 'diff', 'word', 'go', 'figure']
['ever', 'thought', 'living', 'good', 'life', 'perfect', 'partner', 'txt', 'back', 'name', 'age', 'join', 'mobile', 'community', '100p/sms']
['5', 'free', 'top', 'polyphonic', 'tone', 'call', '087018728737', 'national', 'rate', 'get', 'toppoly', 'tune', 'sent', 'every', 'week', 'text', 'subpoly', '81618', 'å£3', 'per', 'pole', 'unsub', '08718727870']
['gud', 'mrng', 'dear', 'hav', 'nice', 'day']
['hoping', 'enjoyed', 'game', 'yesterday', 'sorry', "'ve", 'touch', 'pls', 'know', 'fondly', 'bein', 'thot', 'great', 'week', 'abiola']
['e', 'best', '4', 'ur', 'driving', 'tmr']
['u', 'dogbreath', 'sounding', 'like', 'jan', 'c', 'thatåõs', 'al']
['omg', 'want', 'scream', 'weighed', 'lost', 'weight', 'woohoo']
['generally', "n't", 'one', "'s", 'uncountable', 'noun', 'u', 'dictionary', 'piece', 'research']
["'s", 'really', 'getting', 'hanging', 'around']
['orange', 'customer', 'may', 'claim', 'free', 'camera', 'phone', 'upgrade', 'loyalty', 'call', '0207', '153', '9996.', 'offer', 'end', '14thmarch', 'c', "'s", 'apply', 'opt-out', 'availa']
['\\petey', 'boy', 'whereare', 'friendsare', 'thekingshead', 'come', 'canlove', 'nic\\', "''", "''"]
['ok', 'msg', 'u', 'b4', 'leave', 'house']
['gim', 'few\\', "''", 'lt', 'gt', 'minute', 'ago', "''"]
['last', 'chance', 'claim', 'ur', 'å£150', 'worth', 'discount', 'voucher', 'today', 'text', 'shop', '85023', 'savamob', 'offer', 'mobile', 'c', 'savamob', 'pobox84', 'm263uz', 'å£3.00', 'sub', '16']
['appt', 'lt', 'time', 'gt', 'fault', 'u', "n't", 'listen', 'told', 'u', 'twice']

In [31]:
!pip install spacy
!python -m spacy download en_core_web_sm

Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.24.0)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.2.25)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: typer>=0.24.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (0.24.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.1)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.2)
Requirement already satisfied: click>=8.2.1 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (2.19.2)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer>=0.24.0->typer-slim<1.0.0,>=0.3.0->spacy) (0.1.2)
Collecting en-core-web-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 79.1 MB/s eta 0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')
⚠ Restart to reload dependencies
If you are in a Jupyter or Colab notebook, you may need to restart Python in
order to load all the package's dependencies. You can do this by selecting the
'Restart kernel' or 'Restart runtime' option.

In [32]:
import spacy
from collections import Counter
import pandas as pd

nlp = spacy.load("en_core_web_sm")

In [33]:
def preprocess_spacy(text):
    doc = nlp(text.lower())  # Lowercase + tokenize
    tokens = [token.lemma_ for token in doc
              if not token.is_stop and token.is_alpha]  # remove stopwords & punctuation
    return tokens

# Apply to dataframe column
df['processed'] = df['cols'].apply(preprocess_spacy)
print(df[['cols','processed']].head())

                                                cols  \
0  Go until jurong point, crazy.. Available only ...
1                      Ok lar... Joking wif u oni...
2  Free entry in 2 a wkly comp to win FA Cup fina...
3  U dun say so early hor... U c already then say...
4  Nah I don't think he goes to usf, he lives aro...

                                           processed
0  [jurong, point, crazy, available, bugis, n, gr...
1                       [ok, lar, joke, wif, u, oni]
2  [free, entry, wkly, comp, win, fa, cup, final,...
3                         [u, dun, early, hor, u, c]
4                        [nah, think, go, usf, live]

/tmp/ipykernel_580/2317861071.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['processed'] = df['cols'].apply(preprocess_spacy)

In [34]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Join tokens back to string for TF-IDF
df['processed_text'] = df['processed'].apply(lambda x: " ".join(x))

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(df['processed_text'])

print("TF-IDF Feature size:", X_tfidf.shape)

TF-IDF Feature size: (5572, 5979)